
Vagrant.configure("2") do |config|
  
  config.vm.box = "centos/7" #imagem
  config.vm.hostname = "control-node" #nome
  config.vm.network "private_network", ip: "192.168.56.2"#rede privada
  config.vm.synced_folder ".", "/vagrant", type: "nfs" #config do folder synced
  config.vm.provision "shell", path: "provision.sh" #sh de config

end
