
Vagrant.configure("2") do |config|
  
    config.vm.box = "centos/7" #imagem
    config.vm.hostname = "app01" #nome
    config.vm.network "private_network", ip: "192.168.56.3" #rede privada
    config.vm.network "forwarded_port", guest: 8080, host: 8080
    config.vm.provision "shell", path: "provision.sh"
  end