Vagrant.configure("2") do |config|
  
    config.vm.box = "centos/7" #imagem
    config.vm.hostname = "db01" #nome
    config.vm.network "private_network", ip: "192.168.56.4" #rede privada
    config.vm.network "forwarded_port", guest: 3306, host: 3306
    config.vm.provision "shell", path: "provision.sh"
  end